SELECT
    B.AUTHOR_ID,
    A.AUTHOR_NAME,
    B.CATEGORY,
    SUM(S.SALES * B.PRICE) AS TOTAL_SALES
FROM
    BOOK AS B,
    AUTHOR AS A,
    BOOK_SALES AS S
WHERE
    S.SALES_DATE LIKE '2022-01%'
    AND S.BOOK_ID = B.BOOK_ID
    AND B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY
    B.AUTHOR_ID, B.CATEGORY
ORDER BY
    B.AUTHOR_ID, B.CATEGORY DESC;