# SELECT
#     CART_ID
# FROM
#     CART_PRODUCTS
# GROUP BY
#     CART_ID
# HAVING
#     GROUP_CONCAT(NAME) LIKE '%Yogurt%'
#     AND GROUP_CONCAT(NAME) LIKE '%Milk%'
# ORDER BY
#     CART_ID;

SELECT
    CART_ID
FROM
    CART_PRODUCTS
WHERE
    NAME IN ('Milk', 'Yogurt')
GROUP BY
    CART_ID
HAVING
    COUNT(DISTINCT NAME) = 2
ORDER BY
    CART_ID;