# 1. CONV() 사용
# SELECT COUNT(*) AS COUNT
# FROM ECOLI_DATA
# WHERE CONV(GENOTYPE, 10, 2) LIKE '1'
# OR CONV(GENOTYPE, 10, 2) LIKE '%01'
# OR CONV(GENOTYPE, 10, 2) LIKE '%01'
# OR CONV(GENOTYPE, 10, 2) LIKE '%100';

# 2. 비트연산자 사용
SELECT COUNT(*) AS COUNT
FROM ECOLI_DATA
WHERE (GENOTYPE & 2 != 2) AND (GENOTYPE & 1 = 1 OR GENOTYPE & 4 = 4);