# SELECT
#     ITEM_ID, ITEM_NAME, RARITY
# FROM
#     ITEM_INFO
# WHERE
#     ITEM_ID IN (
#         SELECT PARENT.ITEM_ID
#         FROM
#             ITEM_TREE AS PARENT
#             LEFT JOIN ITEM_TREE AS CHILD
#             ON PARENT.ITEM_ID = CHILD.PARENT_ITEM_ID
#         GROUP BY
#             PARENT.ITEM_ID
#         HAVING
#             COUNT(CHILD.ITEM_ID) = 0
#     )
# ORDER BY
#     ITEM_ID DESC;
    
SELECT
    PARENT.ITEM_ID, PARENT.ITEM_NAME, PARENT.RARITY
FROM
    ITEM_INFO AS PARENT
    LEFT JOIN ITEM_TREE AS CHILD
    ON PARENT.ITEM_ID = CHILD.PARENT_ITEM_ID
WHERE
    CHILD.PARENT_ITEM_ID IS NULL
ORDER BY
    PARENT.ITEM_ID DESC;