SELECT ORIG.FOOD_TYPE, ORIG.REST_ID, ORIG.REST_NAME, ORIG.FAVORITES
FROM
    REST_INFO AS ORIG,
    (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
     FROM REST_INFO
     GROUP BY FOOD_TYPE) AS SUB
WHERE
    ORIG.FOOD_TYPE = SUB.FOOD_TYPE
    AND ORIG.FAVORITES = SUB.FAVORITES
ORDER BY
    ORIG.FOOD_TYPE DESC;