SELECT
    YEAR(B.SALES_DATE) AS YEAR,
    MONTH(B.SALES_DATE) AS MONTH,
    A.GENDER,
    COUNT(DISTINCT A.USER_ID) AS USERS # DISTINCT로 중복 제거해 해당 COL의 종류 개수를 알 수 있다.
FROM
    USER_INFO AS A
    JOIN ONLINE_SALE AS B
    ON A.USER_ID = B.USER_ID
WHERE
    GENDER IS NOT NULL
GROUP BY
    YEAR, MONTH, A.GENDER
ORDER BY 1, 2, 3;