SELECT
    SUB.YEAR,
    SUB.MONTH,
    SUB.GENDER,
    COUNT(SUB.USERS) AS USERS
FROM
    (SELECT
        YEAR(B.SALES_DATE) AS YEAR,
        MONTH(B.SALES_DATE) AS MONTH,
        A.GENDER,
        COUNT(A.USER_ID) AS USERS
    FROM
        USER_INFO AS A
        JOIN ONLINE_SALE AS B
        ON A.USER_ID = B.USER_ID
    WHERE
        GENDER IS NOT NULL
    GROUP BY
        YEAR, MONTH, A.GENDER, A.USER_ID) AS SUB
GROUP BY
    SUB.YEAR, SUB.MONTH, SUB.GENDER
ORDER BY
    SUB.YEAR, SUB.MONTH, SUB.GENDER;