# SELECT COUNT(T.FISH_TYPE) AS FISH_COUNT, N.FISH_NAME
# FROM FISH_INFO AS T JOIN FISH_NAME_INFO AS N ON T.FISH_TYPE = N.FISH_TYPE
# GROUP BY T.FISH_TYPE
# ORDER BY COUNT(T.FISH_TYPE) DESC;

SELECT COUNT(T.FISH_TYPE) AS FISH_COUNT, N.FISH_NAME
FROM FISH_INFO AS T JOIN FISH_NAME_INFO AS N ON T.FISH_TYPE = N.FISH_TYPE
GROUP BY T.FISH_TYPE
ORDER BY COUNT(T.FISH_TYPE) DESC;