WITH TOTAL_COUNT AS (
    SELECT
        COUNT(*) AS CNT
    FROM
        USER_INFO
    WHERE
        YEAR(JOINED) = 2021
)

SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(USER_ID) / TOTAL_COUNT.CNT, 1) AS PUCHASED_RATIO
FROM
    ONLINE_SALE,
    TOTAL_COUNT
WHERE
    USER_ID IN (
        SELECT
            USER_ID
        FROM
            USER_INFO
        WHERE
            YEAR(JOINED) = 2022
    ) AND YEAR(SALES_DATE) = 2022
GROUP BY
    YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY
    YEAR, MONTH;