with USER AS (
    select USER_ID
    from USER_INFO
    where YEAR(JOINED) = 2021
), CNT AS (
    select COUNT(*) TOTAL
    from USER_INFO
    where YEAR(JOINED) = 2021
)
select
    YEAR(SALES_DATE) YEAR,
    MONTH(SALES_DATE) MONTH,
    COUNT(distinct O.USER_ID) PURCHASED_USERS,
    ROUND(COUNT(distinct O.USER_ID) / CNT.TOTAL, 1) PUCHASED_RATIO
from USER U join ONLINE_SALE O on U.USER_ID = O.USER_ID, CNT
group by YEAR, MONTH
order by YEAR, MONTH;


# WITH TOTAL_COUNT AS (
#     SELECT
#         COUNT(*) AS CNT
#     FROM
#         USER_INFO
#     WHERE
#         YEAR(JOINED) = 2021
# )

# SELECT
#     YEAR(SALES_DATE) AS YEAR,
#     MONTH(SALES_DATE) AS MONTH,
#     COUNT(DISTINCT USER_ID) AS PUCHASED_USERS,
#     ROUND(COUNT(DISTINCT USER_ID) / TOTAL_COUNT.CNT, 1) AS PUCHASED_RATIO
# FROM
#     ONLINE_SALE,
#     TOTAL_COUNT
# WHERE
#     USER_ID IN (
#         SELECT
#             USER_ID
#         FROM
#             USER_INFO
#         WHERE
#             YEAR(JOINED) = 2021
#     )
# GROUP BY
#     YEAR(SALES_DATE), MONTH(SALES_DATE)
# ORDER BY
#     YEAR, MONTH;