# SELECT *
# FROM
#     (SELECT
#         CAR_ID,
#         CASE
#             WHEN START_DATE <= '2022-10-16' AND '2022-10-16' <= END_DATE THEN '대여중'
#             ELSE '대여 가능'
#         END AS AVAILABILITY
#     FROM
#         CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     GROUP BY CAR_ID, AVAILABILITY
#     ORDER BY
#         CAR_ID DESC, AVAILABILITY DESC) AS SUB
# GROUP BY SUB.CAR_ID;

SELECT
    A.CAR_ID,
    CASE
        WHEN SUM(A.STATS) = 0 THEN '대여 가능'
        ELSE '대여중'
    END AVAILABILITY
FROM
    (SELECT
        CAR_ID,
        CASE
            WHEN START_DATE <= '2022-10-16' AND '2022-10-16' <= END_DATE THEN 1
            ELSE 0
        END STATS
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY) AS A
GROUP BY
    A.CAR_ID
ORDER BY
    A.CAR_ID DESC;