
select P.PRODUCT_ID, P.PRODUCT_NAME, SUM(O.AMOUNT) * P.PRICE AS TOTAL_SALES
from FOOD_PRODUCT P join FOOD_ORDER O on P.PRODUCT_ID = O.PRODUCT_ID
where O.PRODUCE_DATE like '2022-05%'
group by O.PRODUCT_ID
order by TOTAL_SALES desc, P.PRODUCT_ID;

# SELECT
#     P.PRODUCT_ID,
#     P.PRODUCT_NAME,
#     SUM(O.AMOUNT) * P.PRICE AS TOTAL_SALES
# FROM
#     FOOD_PRODUCT AS P
#     JOIN FOOD_ORDER AS O
#     ON P.PRODUCT_ID = O.PRODUCT_ID
# WHERE
#     O.PRODUCE_DATE LIKE '2022-05%'
# GROUP BY
#     P.PRODUCT_ID
# ORDER BY
#     TOTAL_SALES DESC, P.PRODUCT_ID ASC;