SELECT
    C.HISTORY_ID,
    TRUNCATE(C.DAILY_FEE * (1 - IFNULL(D.DISCOUNT_RATE, 0) * 0.01) * C.DURATION_DAYS, 0) AS FEE
FROM
    (SELECT
        A.HISTORY_ID,
        B.CAR_TYPE,
        B.DAILY_FEE,
        A.CAR_ID,
        TIMESTAMPDIFF(DAY, A.START_DATE, A.END_DATE) + 1 AS DURATION_DAYS,
        CASE
            WHEN TIMESTAMPDIFF(DAY, A.START_DATE, A.END_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN TIMESTAMPDIFF(DAY, A.START_DATE, A.END_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN TIMESTAMPDIFF(DAY, A.START_DATE, A.END_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL
        END AS DURATION_TYPE
    FROM
        CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
        JOIN CAR_RENTAL_COMPANY_CAR AS B
        ON A.CAR_ID = B.CAR_ID
    WHERE
        B.CAR_TYPE = '트럭') AS C
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
    ON D.DURATION_TYPE = C.DURATION_TYPE AND D.CAR_TYPE = C.CAR_TYPE
ORDER BY
    FEE DESC, C.HISTORY_ID DESC;