SELECT
    SUB.FLAVOR
FROM
    (SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
    UNION
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR) AS SUB
GROUP BY
    SUB.FLAVOR
ORDER BY
    SUM(SUB.TOTAL_ORDER) DESC
LIMIT 3;