with MEMBER AS (
    select MEMBER_ID
    from REST_REVIEW
    group by MEMBER_ID
    order by COUNT(MEMBER_ID) desc
    limit 1
)
select P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
from MEMBER_PROFILE P join REST_REVIEW R on P.MEMBER_ID = R.MEMBER_ID, MEMBER
where R.MEMBER_ID = MEMBER.MEMBER_ID
order by REVIEW_DATE, R.REVIEW_TEXT;