SELECT ITEM_INFO.ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO INNER JOIN (SELECT ITEM_TREE.ITEM_ID
FROM ITEM_TREE INNER JOIN (
    SELECT I.ITEM_ID
    FROM ITEM_INFO AS I, ITEM_TREE AS T
    WHERE I.ITEM_ID = T.ITEM_ID
    AND RARITY = 'RARE'
) AS SUB
ON ITEM_TREE.PARENT_ITEM_ID = SUB.ITEM_ID) AS SUB2
ON ITEM_INFO.ITEM_ID = SUB2.ITEM_ID
ORDER BY ITEM_INFO.ITEM_ID DESC;