select COUNT(*) FISH_COUNT, MONTH(TIME) MONTH
from FISH_INFO
group by MONTH(TIME)
order by MONTH;


# SELECT COUNT(*) AS FISH_COUNT, CAST(DATE_FORMAT(TIME, '%c') AS UNSIGNED) AS MONTH
# FROM FISH_INFO
# GROUP BY CAST(DATE_FORMAT(TIME, '%c') AS UNSIGNED)
# HAVING COUNT(*) > 0
# ORDER BY CAST(DATE_FORMAT(TIME, '%c') AS UNSIGNED); # 문자를 정수로 변환

# SELECT COUNT(*) AS FISH_COUNT, MONTH(TIME) AS MONTH
# FROM FISH_INFO
# GROUP BY MONTH(TIME)
# ORDER BY MONTH(TIME);