# SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
# FROM DEVELOPERS
# WHERE
#     SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')
#     OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
# ORDER BY ID;

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE
    SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE NAME IN ('Python', 'C#'))
ORDER BY ID;

# 비트연산자 &는 둘 다 1이면 해당 비트 값 반환(즉, 0보다 큰 수), 둘 중에 하나라도 0이면 0 반환