select
    YEAR(DIFFERENTIATION_DATE) YEAR,
    (
        (select MAX(SIZE_OF_COLONY)
        from ECOLI_DATA
        where YEAR(DIFFERENTIATION_DATE) = YEAR) - SIZE_OF_COLONY
    ) YEAR_DEV, 
    ID
from ECOLI_DATA
order by YEAR, YEAR_DEV;


# SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR, (MD.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV, ED.ID
# FROM ECOLI_DATA AS ED, (
#     SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
#     FROM ECOLI_DATA
#     GROUP BY YEAR
# ) AS MD
# WHERE YEAR(ED.DIFFERENTIATION_DATE) = MD.YEAR
# ORDER BY YEAR, YEAR_DEV;

# SELECT
#     YEAR(DIFFERENTIATION_DATE) AS YEAR,
#     (SELECT MAX(SIZE_OF_COLONY) FROM ECOLI_DATA WHERE YEAR(DIFFERENTIATION_DATE) = YEAR) - SIZE_OF_COLONY AS YEAR_DEV,
#     ID
# FROM ECOLI_DATA
# ORDER BY YEAR, YEAR_DEV;