SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR, (MD.MAX_SIZE - ED.SIZE_OF_COLONY) AS YEAR_DEV, ED.ID
FROM ECOLI_DATA AS ED, (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
) AS MD
WHERE YEAR(ED.DIFFERENTIATION_DATE) = MD.YEAR
ORDER BY YEAR, YEAR_DEV;