# SELECT COUNT(*) AS FISH_COUNT
# FROM FISH_INFO AS I, FISH_NAME_INFO AS N
# WHERE I.FISH_TYPE = N.FISH_TYPE
# AND I.FISH_TYPE IN (0, 1);

# SELECT COUNT(*) AS FISH_COUNT
# FROM FISH_INFO
# WHERE FISH_TYPE IN (0, 1);

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO AS I, FISH_NAME_INFO AS N
WHERE I.FISH_TYPE = N.FISH_TYPE
AND N.FISH_NAME IN ('BASS', 'SNAPPER');