SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT AS D, HR_EMPLOYEES AS E, HR_GRADE AS G
WHERE D.DEPT_ID = E.DEPT_ID
    AND E.EMP_NO = G.EMP_NO
    AND G.YEAR = 2022
GROUP BY G.EMP_NO
ORDER BY SCORE DESC
LIMIT 0, 1;

